version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/eyenet
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here
      - JWT_REFRESH_SECRET=your_refresh_secret_here
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - eyenet-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password123
      - MONGO_INITDB_DATABASE=eyenet
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - eyenet-network
    restart: unless-stopped
    command: mongod --auth

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass secure_redis_pass123
    volumes:
      - redis_data:/data
    networks:
      - eyenet-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secure_password123
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=express_pass123
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_SITE_BASEURL=/mongo-express
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - VCAP_APP_HOST=0.0.0.0
    depends_on:
      - mongodb
    networks:
      - eyenet-network
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secure_redis_pass123
      - HTTP_USER=admin
      - HTTP_PASSWORD=commander_pass123
    depends_on:
      - redis
    networks:
      - eyenet-network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  eyenet-network:
    driver: bridge
